### ISSUE TITLE
Bibliographies and Citations

### ISSUE THREAD

**Issue by rudeboybert** [OpenIntroStat/oilabs-tidy#10]
How do we feel about having bibliographies and citations? This is easily done in [markdown](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html). 

This is more of an aesthetic issue. In particular note the [preamble](http://htmlpreview.github.io/?https://github.com/andrewpbray/oiLabs-base-R/blob/master/multiple_regression/multiple_regression.html) to the Multiple Regression lab.

**Comment by mine-cetinkaya-rundel** [comment]
I have no objections to more formal citations.

**Comment by beanumber** [comment]
I think this is a great idea. It's an easy way to show off a nice feature of Markdown.

**Comment by andrewpbray** [comment]
Hey, I didn't know about this feature. Go for it!
