### ISSUE TITLE
cans of worms opened by ggplot'ification

### ISSUE THREAD

**Issue by rudeboybert** [OpenIntroStat/oilabs-tidy#11]
- The `plot_ss` (SLR lab), `inference`, and `multiLines` (multiple regression lab) rely on base graphics. Upon a cursory look, ggplot'ifying them will take a bit of work, so I wanted to discuss this before jumping down that rabbit hole.
- In the [multiple regression](http://htmlpreview.github.io/?https://github.com/andrewpbray/oiLabs-base-R/blob/master/multiple_regression/multiple_regression.html) lab with teacher eval data, if we want students to create scatterplots of _multiple_ pairs of variables à la `plot(evals[,13:19])` then we'll have to either
  - stick with base R
  - Use the `ggpairs` function in the GGally package, thereby increasing the number of package dependencies.
- In the [simple linear regression](http://htmlpreview.github.io/?https://github.com/andrewpbray/oiLabs-base-R/blob/master/simple_regression/simple_regression.html) lab with MLB data, we ask students to create scatterplots with regression lines and qqplots with qqlines. I don't think there is a way to superimpose such lines without resorting to `stat_smooth(method="lm", se = F)`

What are your thoughts on
- Jumping back and forth between plotting formats in the scenarios above?
- Busting out of self contained `qplot()` calls and using layers?

**Comment by mine-cetinkaya-rundel** [comment]
- I'm working on the `inference` function this weekend, so this will be done soon.
- I actually really like the `ggpairs` function, I'd vote for that

I knew the conversation would come to potentially leaving `qplot` behind for `ggplot` and layers :) I'd be interested in hearing others' ideas. I tried teaching my data science course with `qplot` only last year and it just didn't work, so for that course I'm not even introducing `qplot` this year. 

I think the right way to go about this conversion is not to try to re-create the old labs exactly in dplyr+ggplot2, but instead to re-think what are important skills we can teach them easily using these tools, and what are not worth venturing down the rabbit hole (while still attaining the same statistical learning outcomes of course).

**Comment by andrewpbray** [comment]
- ggplotifying doesn't seem worth it at this point. I think the aesthetic disconnect will be much more apparent to us that to students, so the conversion should be a low priority. What we could and probably should do is modify those functions if need be so that the syntax coheres with `qplot()`.
- I'm fine with going with `ggpairs()`.
- Hmm, I'm not sure what to do here. It seems like a bad idea to introduce the + operator just to add that line. I think I'd opt for wrapping the ggplot layers in a new function.

I definitely agree with Mine that we should for not a direct port from the base r labs (cause that'll lead to all of these special cases that require cludge fixes), but to think about what the main computational statistical learning outcomes are for the relevant chapter, within the dplyr/ggplot2 framework.

**Comment by beanumber** [comment]
What about `pairs()`?

Please see (https://github.com/andrewpbray/oilabs/issues/8) for my thoughts on `plot_ss`, `inference`, and `multiLines`. In short, I wonder if we should be using any of them. 

And yes, in re-writing these labs with `dplyr` it becomes evident that several of the labs need to be re-worked entirely. [Case in point: (https://github.com/andrewpbray/oiLabs-dplyr-ggplot/pull/9)] To really do this right, I wonder if we should try re-writing the labs more or less from scratch.

**Comment by andrewpbray** [comment]
I'm sympathetic to the idea of writing the labs from scratch. I'm two labs in this semester, though, so I'm committed to the current course of dplyr adapted labs from base R. I feel like I'm learning a lot in the process, though, so hopefully there will be some clear ideas to guide the new labs.

**Comment by mine-cetinkaya-rundel** [comment]
I feel like we have addressed the comments raised in this issue adequately in the most recent version of the labs. If all agree I'd like to close.

**Comment by beanumber** [comment]
I'm satisfied.
