### ISSUE TITLE
code to generate histQQmatch in Normal Distributions labs?

### ISSUE THREAD

**Issue by beanumber** [OpenIntroStat/oilabs-tidy#19]
This places a PDF in the wrong directory, then calls a PNG??

```
pdf("histQQmatch.pdf", height = 20, width = 15)
multiplot(p1, p2, p3, p4, p5, p6, p7, p8,
          layout = matrix(1:8, ncol = 2, byrow = TRUE))
dev.off()
```

```
![histQQmatch](more/histQQmatch.png)
```

**Comment by beanumber** [comment]
It should be:

```
![histQQmatch](more/histQQmatchgg.png)
```

**Comment by beanumber** [comment]
The chunk `r hists-and-qqs` seems unnecessarily long and complicated. Might this be improved using `dplyr::do()`?

**Comment by andrewpbray** [comment]
Thanks for catching that. The directory and call to png() are now there. I agree that that final chunk could be cleaned up. It's mostly for the purpose of reproducibility, so it's not a top priority for me for feel free to fiddle.
