### ISSUE TITLE
Residuals vs. standard residuals in simple linear regression lab

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/oilabs-tidy#25]
Looks like the baseball lab uses .stdresid in the residuals plots. I think we should stick with .resid since that is what is in the textbook, and unless I'm missing it the lab doesn't explain what standardized residuals are, and I'd vote against going there... Happy to do a pull request but wanted to discuss it first in case this was a deliberate decision.

**Comment by andrewpbray** [comment]
Thanks for opening an issue on this. It was a partially thought-through decision at least. The main rationale was that I discovered - oh! - if you're working with linear model objects, it's straight-forward to generate a qqplot in ggplot that has that identity line. The lack of line in the normal distribution lab seemed to frustrate students somewhat, so this was an easy fix, though not consistent with the normal dist lab (which doesn't use lm objects) or with the book, apparently.

We _could_ add the line to the non-standardized one, but it's a bit ugly. I guess on balance it's probably best to remove the standardization / line.

Pull request away =)

**Comment by mine-cetinkaya-rundel** [comment]
Yeah, adding the equivalent of the qqline is ugly, I agree that we shouldn't go there. But I hesitate to introduce a whole different way of looking at the plots in the lab that is different from the textbook (and in my case videos as well). Especially because for the students I work with the mapping from residuals & qqline (not that they call it that) to standardized residuals & h = 0 line won't be obvious, and going there would require quite a bit of explanation in the lab. I suggest not worrying about it, and sticking with residuals without the straight line.
