### ISSUE TITLE
Convert all data files to RData?

### ISSUE THREAD

**Issue by andrewpbray** [OpenIntroStat/oilabs-tidy#3]
Looks like we've been sourcing .R files for the labs that don't have custom functions. Seems really awkward to have the data in an R script. The most straightfoward fix would be to have them download and load an RData file instead, which is what the latter labs do anyway. Here's an [example](https://github.com/andrewpbray/oiLabs-dplyr/commit/f8f0750f188865832dacccfde8b97982723e760c).

Even better is putting it all in the oiLabs package. Are there any arguments in favor of keeping the data hosted on the openintro website instead of in a package on github?

**Comment by beanumber** [comment]
I'm wholeheartedly in favor of putting **all** of the data files in the `openintro` R package!!! That way everything is just:

```
require(openintro)
data(whatever)
```

Also, I think it's important that we move all of the **functions** in those sources files into the `openintro` package. These are not documented and that breaks the support workflow for students (and me).

**Comment by mine-cetinkaya-rundel** [comment]
Agreed about moving functions into package, with proper help files.

As well as moving the data there.

**Comment by andrewpbray** [comment]
Well shoot: i just went to create an oilabs package, but github won't allow dual-named repos. What do you think about renaming the base r labs repo to oiLabs-base-R?

**Comment by mine-cetinkaya-rundel** [comment]
That sounds fine to me.

The R package won't be lab format specific though, right? So for all versions of labs we'll just be able to use the following?

```
require(openintro)
data(whatever) 
```

**Comment by andrewpbray** [comment]
I just got off the phone with David, discussing the pros and cons of having the two packages separate, which is what we initially imagined I think, versus combined. We're both leaning towards just one openintro package since it's hard to think of any real cons. David's going to think it over and get back to us tomorrow.

**Comment by beanumber** [comment]
In general, it makes sense to me to have just one package for `openintro`. Whether you use the labs or not, there's very little harm done by putting the lab stuff in the main package, and as you've discovered, having many packages may just get confusing.

**Comment by andrewpbray** [comment]
After talking with David, it seems to make sense to go for a separate `oilabs` package for now. The main reasons are that this package will depend on `dplyr`, `ggplot2`, and `mosaic` and we'll be adding templates and that's a lot of overhead for the users of the `openintro` package that aren't using the labs. We can always fold it in at a later date.

So, the naming scheme is set up to be:
1. `oilabs`: the package for the labs containing data, custom functions, documentation, and templates.
2. `oiLabs-base-R`: this is the original labs repo that had been called `oiLabs`.
3. `oiLabs-hadleyverse`: for the new set of labs that'll use `dplyr` + `qplot()` + `do()`, currently called `oiLabs-dplyr`. I haven't made this change yet, so please weigh in with your thoughts, @mine-cetinkaya-rundel , @beanumber , @rudeboybert .

**Comment by mine-cetinkaya-rundel** [comment]
Keeping `openintro` and `oilabs` packages sounds fine, but I'm thinking there might not be a need to separate `-base-R` and `-hadleyverse`? If we're going to be putting the templates together, these should be fore both `-base-R` and `-hadleyverse` labs anyway, as well as others like mosaic.

Another advantage for keeping everything lab related in one package is from the student perspective. Words like base R or Hadleyverse likely don't mean anything to students for whom these labs are intended for, and it seems an additional burden to explain what they mean.

**Comment by andrewpbray** [comment]
Ah, I was a bit unclear here. I'm also envisioning only one labs package but multiple repos with each variant of the labs.

**Comment by mine-cetinkaya-rundel** [comment]
That works for me.

**Comment by rudeboybert** [comment]
SGTM
