### ISSUE TITLE
remove GGally dependency?

### ISSUE THREAD

**Issue by beanumber** [OpenIntroStat/oilabs-tidy#36]
This seems like an awful big hammer. Why not:

```
evals %>%
  select(contains("bty")) %>%
  pairs()
```

**Comment by mine-cetinkaya-rundel** [comment]
It's there because `pairs()` doesn't give ggplot style plots.

I'm open to an alternative solution, but curious, why call it a "awful big hammer"? As in, what is the downside?

**Comment by beanumber** [comment]
I see. I think maybe I was thinking of a different package.
