### ISSUE TITLE
www/lab.css?

### ISSUE THREAD

**Issue by beanumber** [OpenIntroStat/oilabs-tidy#38]
Is there a reason why labs 5 and 8 use a custom CSS? The CSS files themselves aren't different. Is this because of the Shiny stuff?

**Comment by mine-cetinkaya-rundel** [comment]
They all use the same custom CSS. If the Rmd document with Shiny uses a CSS it needs to be saved in a subfolder called www. That's the difference for these two labs. (Now that I think of it, this was true as of ~year ago when I first wrote these labs. Possible there may have been an update that doesn't necessitate it. I'll look into it.)

**Comment by mine-cetinkaya-rundel** [comment]
looks like css does need to live in a separate folder: http://shiny.rstudio.com/articles/css.html

**Comment by beanumber** [comment]
I'd suggest a flatter file structure and the use of the `docs/` folder to use `gh-pages`. I've done some of this is the (https://github.com/beanumber/oiLabs-mosaic) repo. 

I understand why you set it up to have each lab in its own folder, but I'm not sure if those arguments are compelling. Is the stuff in the `more` directories necessary? Hasn't all of that information been pushed to the `oilabs` package?

**Comment by mine-cetinkaya-rundel** [comment]
Stuff in the `more` directories may no longer be necessary. I'm holding on to them for now until the `oilabs` package is finalized and then I'm planning to do a sweep to clean the repo. At that time we'll also move this repo to the OpenIntroOrg organization (which hopefully won't break a million things, we'll see).

What exactly do you mean by flatter structure? All Rmds in the root folder? For some reason that seems messy to me, but if it makes something else easier (like `gh-pages`) that might be a compelling enough argument.

**Comment by beanumber** [comment]
Yes, in the root folder, or in a single `Rmd` folder. Basically you could
set this up as an R Markdown website, with the `docs/` directory being the
`output_dir`:

(http://rmarkdown.rstudio.com/rmarkdown_websites.html#overview)

**Comment by mine-cetinkaya-rundel** [comment]
Ok I'll take a look. I'm ok with making things easier for hosting, as long as the underlying code doesn't get too complicated for a teacher with less R experience to take a single lab and modify and use if that's what they want to do. I don't think what you're suggesting would cause that so it seems doable to me, but that's usually what I have in mind when I'm making changes to the source files.
