### ISSUE TITLE
add five single-table verbs to "intro to data" lab

### ISSUE THREAD

**Issue by beanumber** [OpenIntroStat/oilabs-tidy#43]
I just finished the "Intro to Data" lab. It went OK, but I recommend:
- renaming this "Intro to Data Wrangling"
- introducing the five single-table verbs at the beginning (e.g. `select`, `filter`, `mutate`, `arrange`, and `summarize`)
- including a short discussion of the "grammar of data manipulation"
- focusing the content on applications of the five verbs and creating simple pipelines
- keeping the `group_by` stuff, as I think this is a necessary skill

Without the discussion of the five single table verbs I'm not sure how we expect students to assimilate these skills.

**Comment by mine-cetinkaya-rundel** [comment]
Thanks for the feedback @beanumber. By "focusing the content on applications of the five verbs and creating simple pipelines" do you mean to the exercises should be explicitly worded around these verbs? I would be more in favor of "do this with the data" and the answer is "this word will help you do it", than "here is how we can use the filter function with the data" type approach. Let me know if that's not clear, I can give examples.

**Comment by beanumber** [comment]
No, I don't really have a problem with the exercises. They could be clearer in some cases, but what I meant was that the modular nature of the verbs (`data.frame` in, `data.frame` out) could be emphasized in a way that would make it clearer to students that you can create complex operations by chaining simple operations together. I would include the pictograms from the cheat sheets, too.
