### ISSUE TITLE
use of ABs as explanatory variable in SLR lab?

### ISSUE THREAD

**Issue by beanumber** [OpenIntroStat/oilabs-tidy#45]
What was the thinking behind making `at_bats` the central explanatory variable in the SLR lab? It's not very intuitive for me. The most obvious explanatory variables would be `home_runs` or `hits` or `bat_avg`, all of which measure offensive production. `at_bats` sort of measures offensive _opportunities_, and it is correlated with `runs` because of the fact that innings end after three outs, but can go on forever. So if your team makes outs at a lower rate, then you get more plate appearances per inning, and thus more `at_bats` per inning, and along the way presumably more `runs`. So it is not surprising that there is a strong positive correlation, but it is a very backwards and counter-intuitive way of thinking about explaining the variability in team runs scored.

**Comment by mine-cetinkaya-rundel** [comment]
I am not sure. The very original version of this lab was written at UCLA by someone who I think knows about sports in general, but my guess is you have a better intuition when it comes to baseball. I'm personally happy to take your advice on this. I have no idea which variable makes more sense.  Do you have a suggestion as to which of the three you mentioned to replace `at_bats` with?

**Comment by beanumber** [comment]
Probably batting average. I don't have the cycles to change this right now, but I think it would be more intuitive if we made that change at some point.

**Comment by mine-cetinkaya-rundel** [comment]
Ok I'll see if I can get to it when I'm making a couple other changes by next week. I'll leave this open for now as a reminder.

**Comment by mine-cetinkaya-rundel** [comment]
No longer using the baseball data, so I'll close this one.
