### ISSUE TITLE
ambiguity in Exercise 10 on intro to data lab

### ISSUE THREAD

**Issue by beanumber** [OpenIntroStat/oilabs-tidy#48]
In Exercise 10, there is some ambiguity in the definition of "on time". A flight gets `arr_type` as `on time` if the delay is <= 0 minutes. However, previously in the lab, `dep_type` was defined as `on time` if it was less than 5 minutes late.  Do you expect that students will re-define `dep_type` with a definition that matches that of `arr_type` in Exercise 10? Or simply use the previous definition, which is logically mismatched? Apparently, virtually all of my students did the latter.

**Comment by mine-cetinkaya-rundel** [comment]
Ah I caught this the other day in the Coursera course. I'll push a fix.

**Comment by beanumber** [comment]
What was intended??

**Comment by mine-cetinkaya-rundel** [comment]
The intention was to stick with the old definition of `dep_type` (just to avoid defining the same variable again), it just wasn't clear from the wording.
