### ISSUE TITLE
Reference to R reference card

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/oilabs-tidy#5]
I suggest removing the following in https://github.com/andrewpbray/oiLabs-dplyr-ggplot/blob/master/intro_to_r/intro_to_r.Rmd:

_You can refer to the help files or the R reference card http://cran.r-project.org/doc/contrib/Short-refcard.pdf to find helpful commands._

since it doesn't really have dplyr / ggplot2 help. We could replace it with references to the [RStudio Cheatsheets](https://www.rstudio.com/resources/cheatsheets/) if desired.

**Comment by andrewpbray** [comment]
agreed and fixed (removed).
