### ISSUE TITLE
switch to tidyverse?

### ISSUE THREAD

**Issue by beanumber** [OpenIntroStat/oilabs-tidy#55]
Can we rename this project `oiLabs-tidyverse` and use `library(tidyverse)` at the beginning of each lab?

**Comment by mine-cetinkaya-rundel** [comment]
Great idea! Let's do that when we transition the repo to openintroorg,
which is soon.
On Wed, Jan 25, 2017 at 10:54 AM Ben Baumer <notifications@github.com>
wrote:

> Can we rename this project oiLabs-tidyverse and use library(tidyverse) at
> the beginning of each lab?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_andrewpbray_oiLabs-2Ddplyr-2Dggplot_issues_55&d=CwMCaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=VMaFnDxOO7DFh_jmcYrq6Oi2_V_d1YoR6dsQ-kCSJjw&m=Z90w2I-BOHYPYdZEf0-vLZtEtPiRyWzhEPDiTidHSUY&s=DlrqBRfooY3fbSy5y3KRwmJA-18AyjHDvGRyu3IZAMA&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFsHUYsUydb7kYPYHGuhekeK1VWztAsCks5rV3AcgaJpZM4Ltpno&d=CwMCaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=VMaFnDxOO7DFh_jmcYrq6Oi2_V_d1YoR6dsQ-kCSJjw&m=Z90w2I-BOHYPYdZEf0-vLZtEtPiRyWzhEPDiTidHSUY&s=GRKs7L3r8zgcKzPhmRuiRmhX1VIrx7H6f2TiOUtkj3Y&e=>
> .
>
-- 
Mine Çetinkaya-Rundel, Ph.D.
Director of Undergraduate Studies
Associate Professor of the Practice
Duke University, Department of Statistical Science
<mine@stat.duke.edu> mine@stat.duke.edu
<https://stat.duke.edu/~mc301/> https://stat.duke.edu/~mc301
<https://github.com/mine-cetinkaya-rundel>  <https://twitter.com/minebocek>
<http://citizen-statistician.org/>

**Comment by mine-cetinkaya-rundel** [comment]
Done!
