### ISSUE TITLE
Language about RStudio server + instructor help

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/oilabs-tidy#6]
This is in reference to https://github.com/andrewpbray/oiLabs-dplyr-ggplot/blob/master/intro_to_r/intro_to_r.Rmd:

Since these labs are for wider distribution, for the generic versions (to be hosted on OpenIntro) I suggest we remove references to the RStudio server. 

Also in the past we've made an effort to avoid language like "ask me", "ask TAs", etc. so that self learners or those at institutions with different structures could also adopt the labs easily.

**Comment by andrewpbray** [comment]
Yeah. Since the people that will be using it this fall will all be using the server (I think?) I was thinking this would work for now, then we could do the wide-distribution changes at the end of the semester when (hopefully) the package would be all set on CRAN. Are you using the server?

**Comment by mine-cetinkaya-rundel** [comment]
I am using the server.

I'm ok with changing these before release, then let's keep this issue open so we don't forget.

**Comment by mine-cetinkaya-rundel** [comment]
I think we took care of all of these in the most recent versions of the labs.

**Comment by beanumber** [comment]
Can we, however, soften the directive to install packages first? My students will be working the RStudio Server and I definitely don't want them installing `dplyr` (which needs compilation) at the same time. 

Would you consider a PR that instead of 

> First, install these packages...

Says something like,

> If these packages aren't already installed in your R environment, install them...

**Comment by mine-cetinkaya-rundel** [comment]
Sure, that would work. As long as we leave the install instructions in there.
