### ISSUE TITLE
error when knitting intro_to_data.Rmd

### ISSUE THREAD

**Issue by jricoiii** [OpenIntroStat/oilabs-tidy#66]
I first had to do some edits to get the nycflights to load
By entering this into the console

install.packages command is needed in the consule
install.packages("tidyverse")
install.packages("devtools")
library(devtools)
install_github("OpenIntroStat/openintro-r-package")

Then when knitting I get error on Line 374
error in eval(lhs, parent, parent) :" object 'nycflights' not found 

My file is at 
https://github.com/ohlone-math159/lab-02-intro-to-data/blob/master/02_intro_to_data/intro_to_data.Rmd

**Comment by jricoiii** [comment]
I can run the chunk containing line 374, but it will not knit.

**Comment by jricoiii** [comment]
I worked around it by removing the chunk and replacing it with an image of the plot since that's what is actually needed in the assignment (replicate the graph)

![Plot to Replicate](../Rplot.png)

**Comment by jricoiii** [comment]
Tried to knit again and now got this error
output file: intro_to_data.knit.md


Access violation in generated code when executing data at 0x8bac658

 Attempting to reconstruct a stack trace...

   Frame	Code address
 * 0x57adac0	0x8bac658

Error: pandoc document conversion failed with error 11
Execution halted

**Comment by mine-cetinkaya-rundel** [comment]
@jricoiii I'm unable to reproduce this, can you share your `sessionInfo()`?

**Comment by mine-cetinkaya-rundel** [comment]
This should all be working now.
