### ISSUE TITLE
kobe_basket data set is missing

### ISSUE THREAD

**Issue by kgilds** [OpenIntroStat/oilabs-tidy#69]
Hey, I think a data set is missing to run the [Probability Lab](http://openintrostat.github.io/oiLabs-tidy/03_probability/probability.html). In the openintro package, there does not appear to be a data set called kobe_basket. I attempted to work around with the data files in the repo but am not able to find a data-set call kobe_basket or a data set with a variable called shot.

**Comment by mine-cetinkaya-rundel** [comment]
The dataset is in the development version of the package, which is on its way to CRAN soon! For now you can install it with 

```r
library(devtools)
install_github("OpenIntroStat/openintro")
```

You can find the documentation [here](http://openintrostat.github.io/openintro/reference/kobe_basket.html).

**Comment by kgilds** [comment]
Thank you!
