### ISSUE TITLE
"conditioning commands"

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/oilabs-tidy#7]
In intro_to_data we use the term "conditioning commands", but a quick search yields we might be the only ones calling these that. Should we be looking for different terminology? They're not really "conditioning"... They're typically called "logical operators". If we wanted to avoid that language, we might want to think of something closer to that.

Note that if we were to make a change here we would want to carry it across other versions of these labs as well.

**Comment by andrewpbray** [comment]
Agreed and fixed with the commit below. We'll have to keep an eye out for this in future labs.

https://github.com/andrewpbray/oiLabs-dplyr-ggplot/commit/e2a03ea3b46f3dcc94e18f2bcf48a51cbc67a35d
