### ISSUE TITLE
SLR Lab Exercise 8 Has No Correct Answer

### ISSUE THREAD

**Issue by dpwynne** [OpenIntroStat/oilabs-tidy#74]
I am passing on an issue pointed out by an instructor trying to use the Rguroo labs. The same issue exists in the tidyverse lab.

Exercise 8 in the tidyverse lab asks the student to compute the residual for a country with pf_expression_control = 7.4. However, the pf_expression_control scores are rated to the nearest 0.25 of a point. So it is impossible to compute a residual in this exercise.

**Comment by mine-cetinkaya-rundel** [comment]
Thanks for pointing this out. It alerted me to a logical inconsistency throughout the lab -- fitting a model to data from all years doesn't really make sense. I've made a series of updates to address this in the commit referenced above.
