### ISSUE TITLE
SLR Lab Correlation Code Produces NA

### ISSUE THREAD

**Issue by dpwynne** [OpenIntroStat/oilabs-tidy#75]
This code right before the Sum of squared residuals section:

`hfi %>%
  summarise(cor(pf_expression_control, pf_score))`

produces an NA value. I am not sure whether you prefer to fix with

`hfi %>%
  summarise(cor(pf_expression_control, pf_score, use = "complete.obs"))`

or

`hfi_small_clean %>%
  summarise(cor(pf_expression_control, pf_score))`

**Comment by mine-cetinkaya-rundel** [comment]
Fixed, thank you! Using `hfi_small_clean` makes more sense with the flow of the lab I think.
