### ISSUE TITLE
Testing the labs while writing them with global chunk options

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/oilabs-tidy#8]
The final version of the labs usually has `eval = FALSE` for all code chunks, since we show the code and not the output. However when writing the lab we want to make sure all code runs properly. I found the following approach an easier way to make sure of this than what we're doing currently:
- Add the following chunk on top of the lab with the option `include = FALSE` so it doesn't show up in the lab

``` r global_options, include=FALSE
knitr::opts_chunk$set(eval = TRUE/FALSE)
```
- In this chunk set `eval = TRUE` when testing, and convert to `eval = FALSE` when done testing before publishing. 
- Remove `eval = FALSE` statements from the individual code chunks in the lab

Note that this can be applied to other versions of the labs as well

**Comment by beanumber** [comment]
Nice.

**Comment by andrewpbray** [comment]
I like this a lot.
